# Generated by Django 4.1.5 on 2023-01-27 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_paid_until_alter_account_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='paid_until',
            field=models.DateField(default=datetime.date(2023, 1, 28)),
        ),
    ]
