# Generated by Django 4.1.5 on 2023-01-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menuName',
            new_name='name',
        ),
    ]
