# Generated by Django 4.1.5 on 2023-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_menuname_menu_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
