# Generated by Django 4.1.5 on 2023-01-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_category_image_alter_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=12, editable=False),
            preserve_default=False,
        ),
    ]
