# Generated by Django 4.1.5 on 2023-01-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='background_image',
            field=models.ImageField(default='menus_backgrounds/default.jpg', upload_to='menus_backgrounds'),
        ),
    ]
