# Generated by Django 4.1.5 on 2023-01-26 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_menu_background_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='account',
            new_name='user',
        ),
    ]
